### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder

### ISSUE THREAD

**Issue by vysak** [UniconLabs/cas-strap-sample#1]
I did a fresh checkout and ran the command I am getting the following error, and couldn't come out of it.

> ./gradlew run
> Starting a new Gradle Daemon for this build (subsequent builds will be faster).
> :compileJava UP-TO-DATE
> :processResources
> :classes
> :war
> :run
> Failed to instantiate SLF4J LoggerFactory
> Reported exception:
> java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
>   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1617)
>   at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
>   at org.slf4j.LoggerFactory.bind(LoggerFactory.java:143)
>   at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:122)
>   at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:378)
>   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:328)
>   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
>   at org.jasig.cas.web.init.SafeContextLoaderListener.<init>(SafeContextLoaderListener.java:62)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
>   at java.lang.Class.newInstance(Class.java:442)
>   at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
>   at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4876)
>   at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
>   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>   at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
>   at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 35 more
> Error configuring application listener of class org.jasig.cas.web.init.SafeContextLoaderListener
> java.lang.NoClassDefFoundError: org/slf4j/spi/LoggerFactoryBinder
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
>   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1617)
>   at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
>   at org.slf4j.LoggerFactory.bind(LoggerFactory.java:143)
>   at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:122)
>   at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:378)
>   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:328)
>   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
>   at org.jasig.cas.web.init.SafeContextLoaderListener.<init>(SafeContextLoaderListener.java:62)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
>   at java.lang.Class.newInstance(Class.java:442)
>   at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
>   at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4876)
>   at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
>   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>   at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
>   at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LoggerFactoryBinder
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 35 more
> Skipped installing application listeners due to previous error(s)
> Error listenerStart
> Context [/cas] startup failed due to previous errors
> Started Tomcat Server
> The Server is running at http://localhost:8080/cas

**Comment by scalding** [comment]
You might try cloning/forking [https://github.com/UniconLabs/cas-strap] and start from there. This fork is based on an old version of the cas-strap configuration that appears to not really work any more. Let me know if you run into the same problem with the other repo. Thanks
